<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://freelance-money-hub.vercel.app/</loc>
<changefreq>weekly</changefreq>
<priority>1.0</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/freelance-hourly-rate-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/project-quote-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/invoice-late-fee-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/self-employment-tax-estimator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/currency-adjusted-rate-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/annual-income-to-hourly-rate-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/freelance-profit-margin-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/tools/days-to-invoice-payment-calculator</loc>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/guides/how-to-set-your-freelance-rate</loc>
<changefreq>monthly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/guides/how-to-invoice-international-clients</loc>
<changefreq>monthly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/guides/freelance-tax-basics-by-country</loc>
<changefreq>monthly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/guides/how-to-price-a-fixed-bid-project</loc>
<changefreq>monthly</changefreq>
<priority>0.8</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/about</loc>
<changefreq>monthly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/contact</loc>
<changefreq>monthly</changefreq>
<priority>0.5</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/privacy-policy</loc>
<changefreq>monthly</changefreq>
<priority>0.3</priority>
</url>
<url>
<loc>https://freelance-money-hub.vercel.app/terms</loc>
<changefreq>monthly</changefreq>
<priority>0.3</priority>
</url>
</urlset>
