/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSelfEmploymentTaxEstimatorRouteImport } from './routes/tools.self-employment-tax-estimator'
import { Route as ToolsProjectQuoteCalculatorRouteImport } from './routes/tools.project-quote-calculator'
import { Route as ToolsInvoiceLateFeeCalculatorRouteImport } from './routes/tools.invoice-late-fee-calculator'
import { Route as ToolsFreelanceProfitMarginCalculatorRouteImport } from './routes/tools.freelance-profit-margin-calculator'
import { Route as ToolsFreelanceHourlyRateCalculatorRouteImport } from './routes/tools.freelance-hourly-rate-calculator'
import { Route as ToolsDaysToInvoicePaymentCalculatorRouteImport } from './routes/tools.days-to-invoice-payment-calculator'
import { Route as ToolsCurrencyAdjustedRateCalculatorRouteImport } from './routes/tools.currency-adjusted-rate-calculator'
import { Route as ToolsAnnualIncomeToHourlyRateCalculatorRouteImport } from './routes/tools.annual-income-to-hourly-rate-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSelfEmploymentTaxEstimatorRoute =
  ToolsSelfEmploymentTaxEstimatorRouteImport.update({
    id: '/tools/self-employment-tax-estimator',
    path: '/tools/self-employment-tax-estimator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsProjectQuoteCalculatorRoute =
  ToolsProjectQuoteCalculatorRouteImport.update({
    id: '/tools/project-quote-calculator',
    path: '/tools/project-quote-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsInvoiceLateFeeCalculatorRoute =
  ToolsInvoiceLateFeeCalculatorRouteImport.update({
    id: '/tools/invoice-late-fee-calculator',
    path: '/tools/invoice-late-fee-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsFreelanceProfitMarginCalculatorRoute =
  ToolsFreelanceProfitMarginCalculatorRouteImport.update({
    id: '/tools/freelance-profit-margin-calculator',
    path: '/tools/freelance-profit-margin-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsFreelanceHourlyRateCalculatorRoute =
  ToolsFreelanceHourlyRateCalculatorRouteImport.update({
    id: '/tools/freelance-hourly-rate-calculator',
    path: '/tools/freelance-hourly-rate-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsDaysToInvoicePaymentCalculatorRoute =
  ToolsDaysToInvoicePaymentCalculatorRouteImport.update({
    id: '/tools/days-to-invoice-payment-calculator',
    path: '/tools/days-to-invoice-payment-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCurrencyAdjustedRateCalculatorRoute =
  ToolsCurrencyAdjustedRateCalculatorRouteImport.update({
    id: '/tools/currency-adjusted-rate-calculator',
    path: '/tools/currency-adjusted-rate-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsAnnualIncomeToHourlyRateCalculatorRoute =
  ToolsAnnualIncomeToHourlyRateCalculatorRouteImport.update({
    id: '/tools/annual-income-to-hourly-rate-calculator',
    path: '/tools/annual-income-to-hourly-rate-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/annual-income-to-hourly-rate-calculator': typeof ToolsAnnualIncomeToHourlyRateCalculatorRoute
  '/tools/currency-adjusted-rate-calculator': typeof ToolsCurrencyAdjustedRateCalculatorRoute
  '/tools/days-to-invoice-payment-calculator': typeof ToolsDaysToInvoicePaymentCalculatorRoute
  '/tools/freelance-hourly-rate-calculator': typeof ToolsFreelanceHourlyRateCalculatorRoute
  '/tools/freelance-profit-margin-calculator': typeof ToolsFreelanceProfitMarginCalculatorRoute
  '/tools/invoice-late-fee-calculator': typeof ToolsInvoiceLateFeeCalculatorRoute
  '/tools/project-quote-calculator': typeof ToolsProjectQuoteCalculatorRoute
  '/tools/self-employment-tax-estimator': typeof ToolsSelfEmploymentTaxEstimatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/annual-income-to-hourly-rate-calculator': typeof ToolsAnnualIncomeToHourlyRateCalculatorRoute
  '/tools/currency-adjusted-rate-calculator': typeof ToolsCurrencyAdjustedRateCalculatorRoute
  '/tools/days-to-invoice-payment-calculator': typeof ToolsDaysToInvoicePaymentCalculatorRoute
  '/tools/freelance-hourly-rate-calculator': typeof ToolsFreelanceHourlyRateCalculatorRoute
  '/tools/freelance-profit-margin-calculator': typeof ToolsFreelanceProfitMarginCalculatorRoute
  '/tools/invoice-late-fee-calculator': typeof ToolsInvoiceLateFeeCalculatorRoute
  '/tools/project-quote-calculator': typeof ToolsProjectQuoteCalculatorRoute
  '/tools/self-employment-tax-estimator': typeof ToolsSelfEmploymentTaxEstimatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/annual-income-to-hourly-rate-calculator': typeof ToolsAnnualIncomeToHourlyRateCalculatorRoute
  '/tools/currency-adjusted-rate-calculator': typeof ToolsCurrencyAdjustedRateCalculatorRoute
  '/tools/days-to-invoice-payment-calculator': typeof ToolsDaysToInvoicePaymentCalculatorRoute
  '/tools/freelance-hourly-rate-calculator': typeof ToolsFreelanceHourlyRateCalculatorRoute
  '/tools/freelance-profit-margin-calculator': typeof ToolsFreelanceProfitMarginCalculatorRoute
  '/tools/invoice-late-fee-calculator': typeof ToolsInvoiceLateFeeCalculatorRoute
  '/tools/project-quote-calculator': typeof ToolsProjectQuoteCalculatorRoute
  '/tools/self-employment-tax-estimator': typeof ToolsSelfEmploymentTaxEstimatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/annual-income-to-hourly-rate-calculator'
    | '/tools/currency-adjusted-rate-calculator'
    | '/tools/days-to-invoice-payment-calculator'
    | '/tools/freelance-hourly-rate-calculator'
    | '/tools/freelance-profit-margin-calculator'
    | '/tools/invoice-late-fee-calculator'
    | '/tools/project-quote-calculator'
    | '/tools/self-employment-tax-estimator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/annual-income-to-hourly-rate-calculator'
    | '/tools/currency-adjusted-rate-calculator'
    | '/tools/days-to-invoice-payment-calculator'
    | '/tools/freelance-hourly-rate-calculator'
    | '/tools/freelance-profit-margin-calculator'
    | '/tools/invoice-late-fee-calculator'
    | '/tools/project-quote-calculator'
    | '/tools/self-employment-tax-estimator'
  id:
    | '__root__'
    | '/'
    | '/tools/annual-income-to-hourly-rate-calculator'
    | '/tools/currency-adjusted-rate-calculator'
    | '/tools/days-to-invoice-payment-calculator'
    | '/tools/freelance-hourly-rate-calculator'
    | '/tools/freelance-profit-margin-calculator'
    | '/tools/invoice-late-fee-calculator'
    | '/tools/project-quote-calculator'
    | '/tools/self-employment-tax-estimator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsAnnualIncomeToHourlyRateCalculatorRoute: typeof ToolsAnnualIncomeToHourlyRateCalculatorRoute
  ToolsCurrencyAdjustedRateCalculatorRoute: typeof ToolsCurrencyAdjustedRateCalculatorRoute
  ToolsDaysToInvoicePaymentCalculatorRoute: typeof ToolsDaysToInvoicePaymentCalculatorRoute
  ToolsFreelanceHourlyRateCalculatorRoute: typeof ToolsFreelanceHourlyRateCalculatorRoute
  ToolsFreelanceProfitMarginCalculatorRoute: typeof ToolsFreelanceProfitMarginCalculatorRoute
  ToolsInvoiceLateFeeCalculatorRoute: typeof ToolsInvoiceLateFeeCalculatorRoute
  ToolsProjectQuoteCalculatorRoute: typeof ToolsProjectQuoteCalculatorRoute
  ToolsSelfEmploymentTaxEstimatorRoute: typeof ToolsSelfEmploymentTaxEstimatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/self-employment-tax-estimator': {
      id: '/tools/self-employment-tax-estimator'
      path: '/tools/self-employment-tax-estimator'
      fullPath: '/tools/self-employment-tax-estimator'
      preLoaderRoute: typeof ToolsSelfEmploymentTaxEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/project-quote-calculator': {
      id: '/tools/project-quote-calculator'
      path: '/tools/project-quote-calculator'
      fullPath: '/tools/project-quote-calculator'
      preLoaderRoute: typeof ToolsProjectQuoteCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/invoice-late-fee-calculator': {
      id: '/tools/invoice-late-fee-calculator'
      path: '/tools/invoice-late-fee-calculator'
      fullPath: '/tools/invoice-late-fee-calculator'
      preLoaderRoute: typeof ToolsInvoiceLateFeeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/freelance-profit-margin-calculator': {
      id: '/tools/freelance-profit-margin-calculator'
      path: '/tools/freelance-profit-margin-calculator'
      fullPath: '/tools/freelance-profit-margin-calculator'
      preLoaderRoute: typeof ToolsFreelanceProfitMarginCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/freelance-hourly-rate-calculator': {
      id: '/tools/freelance-hourly-rate-calculator'
      path: '/tools/freelance-hourly-rate-calculator'
      fullPath: '/tools/freelance-hourly-rate-calculator'
      preLoaderRoute: typeof ToolsFreelanceHourlyRateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/days-to-invoice-payment-calculator': {
      id: '/tools/days-to-invoice-payment-calculator'
      path: '/tools/days-to-invoice-payment-calculator'
      fullPath: '/tools/days-to-invoice-payment-calculator'
      preLoaderRoute: typeof ToolsDaysToInvoicePaymentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/currency-adjusted-rate-calculator': {
      id: '/tools/currency-adjusted-rate-calculator'
      path: '/tools/currency-adjusted-rate-calculator'
      fullPath: '/tools/currency-adjusted-rate-calculator'
      preLoaderRoute: typeof ToolsCurrencyAdjustedRateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/annual-income-to-hourly-rate-calculator': {
      id: '/tools/annual-income-to-hourly-rate-calculator'
      path: '/tools/annual-income-to-hourly-rate-calculator'
      fullPath: '/tools/annual-income-to-hourly-rate-calculator'
      preLoaderRoute: typeof ToolsAnnualIncomeToHourlyRateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsAnnualIncomeToHourlyRateCalculatorRoute:
    ToolsAnnualIncomeToHourlyRateCalculatorRoute,
  ToolsCurrencyAdjustedRateCalculatorRoute:
    ToolsCurrencyAdjustedRateCalculatorRoute,
  ToolsDaysToInvoicePaymentCalculatorRoute:
    ToolsDaysToInvoicePaymentCalculatorRoute,
  ToolsFreelanceHourlyRateCalculatorRoute:
    ToolsFreelanceHourlyRateCalculatorRoute,
  ToolsFreelanceProfitMarginCalculatorRoute:
    ToolsFreelanceProfitMarginCalculatorRoute,
  ToolsInvoiceLateFeeCalculatorRoute: ToolsInvoiceLateFeeCalculatorRoute,
  ToolsProjectQuoteCalculatorRoute: ToolsProjectQuoteCalculatorRoute,
  ToolsSelfEmploymentTaxEstimatorRoute: ToolsSelfEmploymentTaxEstimatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
